#!/bin/bash

# usage : $ sudo ./install_guide

sudo apt-get install git

# Download and prepare hal-core
git clone https://github.com/grotius-cnc/hal_core.git /opt/hal-core
sudo chmod +x /opt/hal-core/prepare
sudo /opt/hal-core/./prepare

# Install the ethercat bus  (optional for hal-core) 
wget https://github.com/grotius-cnc/Linux-Pro/releases/download/1.0.0/ethercat-master.deb 
dpkg -i ethercat-master.deb
/opt/ethercat/script/init.d/ethercat restart

# If you don't have installed qt, kdl kinematics, opencascade cad, you can consider to do this now.
# Hal-core is working exstensively with these c++ libraries.  (optional for hal-core) 
wget https://github.com/grotius-cnc/Linux-Pro/releases/download/1.0.0/qt-creator.deb
wget https://github.com/grotius-cnc/Linux-Pro/releases/download/1.0.0/kdl-kinematics.deb

# New wget link with opencascade image support
wget https://github.com/grotius-cnc/oce/releases/download/1.0.1/opencascade.deb

# Dependencies opencascade
sudo apt-get install -y doxygen cmake tcllib tklib tcl-dev tk-dev \
libfreetype-dev libx11-dev libgl1-mesa-dev libfreeimage-dev rapidjson-dev \
libxmu-dev libxi-dev libfreeimage3 libfreeimage-dev ffmpeg

# Install packages
sudo dpkg -i qt-creator.deb kdl-kinematics.deb opencascade.deb

# Install hal-core
sudo /opt/hal-core/./make

# Download & install hal-view
wget https://github.com/grotius-cnc/hal-view/releases/download/1.0.0/halview.deb
sudo dpkg -i halview.deb
sudo chmod +x /opt/hal-core/runtest_halview

# Download & install cam
wget https://github.com/grotius-cnc/cam/releases/download/1.0.0/cam.deb
# Install dependencies for cam
sudo apt-get install -y zenity zenity-common
sudo dpkg -i cam.deb

# Set user permissions to the /opt dir.
sudo chmod -R -f 777 /opt

# Change owner
sudo chown -R $USER /opt

# Change group
sudo chown -R $USER:$USER /opt
