#!/bin/bash

# Install hal-core :
apt-get install -y locales
export LC_ALL=C
export LANGUAGE=en

# Update sources to get dependencies:
cat <<EOF > /etc/apt/sources.list
deb http://ftp.de.debian.org/debian bullseye main contrib non-free
deb-src http://ftp.de.debian.org/debian bullseye main contrib non-free
deb http://security.debian.org/debian-security/ bullseye-security main
deb-src http://security.debian.org/debian-security/ bullseye-security main
deb http://ftp.de.debian.org/debian sid main
EOF
apt-get update

apt-get install -y build-essential 
apt-get install -y libudev-dev
apt-get install -y libboost-all-dev
apt-get install -y libreadline-dev 

# /opt/hal-core/./make
