#!/usr/bin/bash

# Unix command to load the ethercat .xml config
/opt/hal-core/rtlib/./lcec_conf /opt/hal-core/rtlib/ethercat-conf.xml &

# Startup hal-core
cd /opt/hal-core/scripts
. ./rip-environment

cd /opt/hal-core/bin

halcmd stop
halcmd loadrt threads name1=base-thread fp1=0 period1=30000 name2=servo-thread period2=1000000
halcmd loadrt test
halcmd addf the_function servo-thread

halcmd loadrt lcec

halcmd net ec-slaves-responding <= lcec.slaves-responding
halcmd net ec-link-up <= lcec.link-up
halcmd net ec-all-op <= lcec.all-op

halcmd addf lcec.read-all base-thread
halcmd addf lcec.write-all base-thread

halcmd start

halcmd show

# To clean the hal environment :
# $ /opt/hal-core$ /opt/linuxcnc/scripts/halrun -U
