#!/usr/bin/bash

# Clear previous hal-core sessions
/opt/hal-core/scripts/./halrun -U

cd /opt/hal-core/scripts/ && . ./rip-environment

cd /opt/hal-core/bin

halcmd stop

# http://linuxcnc.org/docs/html/hal/rtcomps.html
halcmd loadrt stepgen step_type=0 ctrl_type=v

halcmd start

halcmd show

# To clean the hal environment :
# $ /opt/hal-core$ /opt/linuxcnc/scripts/halrun -U
