#!/bin/bash

# Compile c++ interface lib
cd /opt/hal-core/src/hal/components/skynet/cpp_interface/
make clean
make

# Copy c++ libraries to /rtlib
cp -rf /opt/hal-core/src/hal/components/skynet/cpp_interface/libcyberdyne.so /opt/hal-core/rtlib
cp -rf /opt/hal-core/src/hal/components/skynet/cpp_interface/libcyberdyne.so.1 /opt/hal-core/rtlib
cp -rf /opt/hal-core/src/hal/components/skynet/cpp_interface/libcyberdyne.so.1.0 /opt/hal-core/rtlib
cp -rf /opt/hal-core/src/hal/components/skynet/cpp_interface/libcyberdyne.so.1.0.0 /opt/hal-core/rtlib

# Copy the ruckig lib to /rtlib
cp -rf /opt/hal-core/src/hal/components/skynet/cpp_interface/libruckig/build/libruckig.so /opt/hal-core/rtlib

cd /opt/hal-core/src/hal/components/skynet/hal/

# Compile with halcore
gcc -o halmodule.o -Os -g -I. -I/opt/hal-core/src/rtapi -I/opt/hal-core/src/hal -DUSPACE -fno-fast-math -fno-unsafe-math-optimizations -DRTAPI -D_GNU_SOURCE -Drealtime -D__MODULE__ -I/opt/hal-core/src/rtapi -I/opt/hal-core/src/hal -DSIM -fPIC -Os -c halmodule.c
cc -shared -o skynet.so halmodule.o -Wl,-rpath,/opt/halcore/lib -L/opt/hal-core/lib -lhalcore -lrt -L/opt/hal-core/src/hal/components/skynet/cpp_interface -lcyberdyne

# Copy the kernel module to the /hal-core/rtlib
rm -rf /opt/hal-core/rtlib/skynet.so
cp -rf skynet.so /opt/hal-core/rtlib
