#!/usr/bin/bash

# Clean up previous hal-core sessions
/opt/hal-core/scripts/./halrun -U

# Startup hal-core
cd /opt/hal-core/scripts/ && . ./rip-environment

cd /opt/hal-core/bin

halcmd stop
halcmd loadrt hostmot2 # Fill in your data : [debug_idrom=N] [debug_module_descriptors=N] [debug_pin_descriptors=N] [debug_modules=N] # http://linuxcnc.org/docs/html/man/man9/hostmot2.9.html
halcmd start

halcmd show

# To clean the hal environment :
# $ /opt/hal-core$ /opt/linuxcnc/scripts/halrun -U
