#!/bin/bash
cd /opt/hal-core/src/hal/components/synchrodofs/hal

# Compile with halcore
gcc -o halmodule.o -Os -g -I. -I/opt/hal-core/src/rtapi -I/opt/hal-core/src/hal -DUSPACE -fno-fast-math -fno-unsafe-math-optimizations -DRTAPI -D_GNU_SOURCE -Drealtime -D__MODULE__ -I/opt/hal-core/src/rtapi -I/opt/hal-core/src/hal -DSIM -fPIC -Os -c halmodule.c
cc -shared -o synchrodofs.so halmodule.o -Wl,-rpath,/opt/halcore/lib -L/opt/hal-core/lib -lhalcore -lrt -L/opt/hal-core/src/hal/components/synchrodofs/cpp_interface -lsynchrodofs

# Copy the kernel module to the /hal-core/rtlib
rm -rf /opt/hal-core/rtlib/synchrodofs.so
cp -rf synchrodofs.so /opt/hal-core/rtlib

# Copy the c++ shared lib to the /hal-core/rtlib
cd /opt/hal-core/src/hal/components/synchrodofs/cpp_interface
cp -rf libsynchrodofs.so /opt/hal-core/rtlib
cp -rf libsynchrodofs.so.1 /opt/hal-core/rtlib
cp -rf libsynchrodofs.so.1.0 /opt/hal-core/rtlib
cp -rf libsynchrodofs.so.1.0.0 /opt/hal-core/rtlib

# Optional: Let linux know where to search for extra shared library's.
sudo ldconfig /opt/hal-core/rtlib/

# Runtest
cd /opt/hal-core/scripts && . ./rip-environment
	
	# stop hal.
        halcmd stop
	
	# Load rt component:
        #
        # When using > 3 DoFs increase period2, also change timer in cpp_interface at_time, ~line 52
        halcmd loadrt threads name1=base-thread fp1=0 period1=25000 name2=servo-thread period2=1000000

        # Standard up to 6 DoFs synchronized by time.
        halcmd loadrt synchrodofs nr=3

        halcmd addf synchrodofs.run servo-thread

        # start hal.
        halcmd start

        halcmd setp synchrodofs.enable.0           1        # bool 0-1
        halcmd setp synchrodofs.maxvel.0           100      # max velocity
        halcmd setp synchrodofs.maxacc.0           10       # max acceleration
        halcmd setp synchrodofs.maxjerk.0          5        # max jerk
        halcmd setp synchrodofs.tarpos.0           500      # targetposition

        halcmd setp synchrodofs.enable.1           1
        halcmd setp synchrodofs.maxvel.1           200
        halcmd setp synchrodofs.maxacc.1           10
        halcmd setp synchrodofs.maxjerk.1          5
        halcmd setp synchrodofs.tarpos.1           600

        halcmd setp synchrodofs.enable.2           1
        halcmd setp synchrodofs.maxvel.2           300
        halcmd setp synchrodofs.maxacc.2           10
        halcmd setp synchrodofs.maxjerk.2          5
        halcmd setp synchrodofs.tarpos.2           700

	# Unload rt components and clean up hal:
        # halrun -U

