#ifndef CPP_INTERFACE_GLOBAL_H
#define CPP_INTERFACE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CPP_INTERFACE_LIBRARY)
#  define CPP_INTERFACE_EXPORT Q_DECL_EXPORT
#else
#  define CPP_INTERFACE_EXPORT Q_DECL_IMPORT
#endif

#endif // CPP_INTERFACE_GLOBAL_H
